package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Configuration.baseUrl;
import static com.codeborne.selenide.Selectors.byLinkText;
import static com.codeborne.selenide.Selectors.byName;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class KinopoiskTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Тестирование поиска")
    void generatedTest() {
        step("Открыть https://www.kinopoisk.ru/", () -> {
            open(baseUrl);
        });

        step("в поле поиска ввести \"сериалы\"", () -> {
            $(byName("kp_query")).click();
        });

        step("нажать на лупу", () -> {
            $(byName("kp_query")).val("сериалы").pressEnter();
        });

        step("убедится что открылась страница с сериалами", () -> {
            $(".search_results_topText").shouldHave(text("поиск: сериалы"));
        });
    }

    sleep(1000);
    @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка текста заголовка страницы")
    void titleTest() {
        step("Открыть https://www.kinopoisk.ru/", () ->
                open(baseUrl));

        step("Заголовок страницы содержит текст 'Кинопоиск. Все фильмы планеты.'", () -> {
            String expectedTitle = "Кинопоиск. Все фильмы планеты.";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    sleep(1000);
    @Test
    @Description("Autogenerated test")
    @DisplayName("Журнал в консоли страницы на содержит ошибок")
    void consoleShouldNotHaveErrorsTest() {
        step("Открыть https://www.kinopoisk.ru/", () ->
                open(baseUrl));

        step("В журналах консоли не должно быть текста 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }

    sleep(1000);
    @Test
    @DisplayName("Проверка вкладки Медиа")
    void mediaTest() {
        step("Открыть https://www.kinopoisk.ru/", () ->
                open(baseUrl));

        step("Нажать на вкладку Медиа", () ->
                $(byLinkText("Медиа")).click());

        step("Проверить наличие раздела Новости", () ->
                $(".posts-sidebar__title").shouldHave(text("Новости")));
    }

    sleep(1000);
    @Test
    @DisplayName("Проверка вкладки Онлайн-кинотеатр")
    void onlainTest() {
        step("Открыть https://www.kinopoisk.ru/", () ->
                open(baseUrl));

        step("Нажать на вкладку Онлайн-кинотеатр", () ->
                $(".styles_lightThemeItem__BSbZW:nth-child(2)").click());

        step("Нажать на кнопку 'Попробовать бесплатно до лета'", () ->
                $(".OnBoardingMainSection__content--2NYzG .Button__root--3NyqY").click());

        step("Проверить что открылось окно Регистрации/Авторизации", () ->
                $(".passp-title").shouldHave(text("Войдите или зарегистрируйтесь")));

    }

    sleep(1000);
    @Test
    @DisplayName("Проверка вкладки Билеты в кино")
    void ticketTest() {
        step("Открыть https://www.kinopoisk.ru/", () ->
                open(baseUrl));

        step("Нажать на вкладку Билеты в кино", () ->
                $(byLinkText("Билеты в кино")).click());

        step("В навигаторе по жанрам выбрать Комедия", () ->
                $(byLinkText("комедия")).click());

        step("проверить что в шапке Афиша/комедия", () ->
                $(".block_left").shouldHave(text("Комедия")));
    }

    sleep(1000);
    @Test
    @DisplayName("Проверка открытия главной страницы при нажатиии на логотип Кинопоиск")
    void logoTest() {
        step("Открыть https://www.kinopoisk.ru/", () ->
                open(baseUrl));

        step("Нажать на вкладку Медиа", () ->
                $(byLinkText("Медиа")).click());

        step("Нажать на логотип Кинопоиск", () ->
                $("._2FHE0JsuuIawgZ4kjcJS4D").click());

        step("Проверить что открылась главная страница", () ->
                $(".styles_sidebarContainer__dxNPY").shouldHave(text("Главная")));

    }
}